crypto/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import dashboard
app_name = 'crypto'

urlpatterns = [
    path(route='', view=dashboard.DashboardHome.as_view(), name='dashboard'),
    path(route='deposit/list', view=dashboard.DepositListView.as_view(), name='deposit_list'),
    path(route='deposit/<str:slug>', view=dashboard.DepositDetailView.as_view(), name='deposit_detail'),
    path(route='investment/list', view=dashboard.InvestmentListView.as_view(), name='investment_list'),
    path(route='investment/<str:slug>', view=dashboard.InvestmentDetailView.as_view(), name='investment_detail'),
    path(route='withdrawal/list', view=dashboard.WithdrawalListView.as_view(), name='withdrawal_list'),
    path(route='withdrawal/<str:slug>', view=dashboard.WithdrawalDetailView.as_view(), name='withdrawal_detail'),
    path(route='new/deposit', view=dashboard.DepositCreateView.as_view(), name='new_deposit'),
    path(route='new/investment', view=dashboard.InvestmentCreateView.as_view(), name='new_investment'),
    path(route='new/withdrawal', view=dashboard.WithdrawalCreateView.as_view(), name='new_withdrawal'),

]

crypto_inv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('crypto.urls')),
    path('auth/', include('auth_app.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'main'

urlpatterns = [
    path(route='', view=views.Home.as_view(), name='home'),
]

crypto/views/authentication.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib import messages
from .tokens import account_activation_token
from django.http.response import HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView
from django.contrib.auth.views import (PasswordResetDoneView, PasswordResetConfirmView,
                                        PasswordResetCompleteView, PasswordChangeView,
                                       PasswordChangeDoneView, PasswordResetView)
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic import View
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import (
    AuthenticationForm,
)
from django.urls import reverse_lazy
from crypto.forms import UserRegisterForm

class UserLoginView(View):
    """
     Logs user into dashboard.
    """
    template_name = 'registration/login.html'
    context_object = {"login_form": AuthenticationForm}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context_object)

    def post(self, request, *args, **kwargs):

        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            
            login(request, user)
            messages.success(request, f"Login Successful ! "
                                f"Welcome {user.username}. Update your User profile if you have not done so. Ignore this message if your User profile is upto date.")
            return redirect('ue_app:home')

        else:
            messages.error(request,
                           f"Please enter a correct username and password. Note that both fields may be case-sensitive."
                           )
            return render(request, self.template_name, self.context_object)
        



class PasswordResetView(PasswordResetView):
    template_name = 'registration/pwd_reset_form.html'
    email_template_name = "registration/email_text/password_reset_email.html"
    from_email = 'lekiaprosper@gmail.com'
    subject_template_name = "registration/email_text/password_reset_subject.txt"
    success_url = reverse_lazy("ue_app:password_reset_done")

class PasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/email_text/password_reset_done.html' 

class PasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/email_text/password_reset_confirm.html'
    success_url = reverse_lazy("ue_app:password_reset_complete")

class PasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/email_text/password_reset_complete.html'

class PasswordChangeView(PasswordChangeView):
    template_name = 'registration/email_text/password_change_form.html'
    success_url = reverse_lazy("ue_app:password_change_done")

class PasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'registration/email_text/password_change_done.html'




UserModel = get_user_model()


class UserRegisterView(View):
    """
      View to let users register
    """
    template_name = 'registration/register.html'
    context = {
        "register_form": UserRegisterForm()
    }

    def get(self, request):
        success_message = "Successful"
        self.context['success_message'] = success_message
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):

        register_form = UserRegisterForm(request.POST)

        if register_form.is_valid():
            user = register_form.save(commit=False)
            user.is_active = True
            user.is_staff = True
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('registration/activate_email.html'
                                       , {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
                'protocol': 'http',
            }
            )
            from_email = 'prosperlekia@gmail.com'
            to_email = register_form.cleaned_data.get('email')
            print(to_email)
            print(message)
            email = EmailMessage(
                mail_subject, message, from_email, to=[to_email]
            )
            email.send()

            return HttpResponseRedirect(reverse_lazy('ue_app:email_verification_confirm'))

        else:
            messages.error(request, "Please provide valid information.")
            # Redirect user to register page
            return render(request, self.template_name, self.context)

    def get_success_url(self):
        return reverse('ue_app:home')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(
            request, f'Hi {user.username}, your registration was successful!! .')
        return reverse('ue_app:home')
    else:
        return reverse_lazy('ue_app:email_verification_invalid')


class EmailVerificationConfirm(TemplateView):
    template_name = 'registration/email_verification_confirm.html'


class EmailVerificationInvalid(TemplateView):
    template_name = 'registration/email_verification_invalid.html'

crypto/views/dashboard.py
from typing import Any, Dict
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from crypto.models import Deposit, Investment, Withdrawal, Asset, TransactionSettings, MainAccount, ReferralAccount, ProfitAccount
from crypto.forms import DepositForm, InvestmentForm, WithdrawalForm
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
import random
import string
from decimal import Decimal
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Sum, Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.validators import MinValueValidator
def random_alphanumeric_string():
    return ''.join(
        random.choices(
            string.ascii_letters + string.digits,
            # string.digits,
            k=10
        )
    )

class DashboardHome(LoginRequiredMixin,TemplateView):
    template_name = 'userdashboard/dashboard.html'
    login_url = "auth_app:login"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(DashboardHome, self).get_context_data(**kwargs)

        transaction_settings = get_object_or_404(TransactionSettings, pk=1)
        starting_balance = transaction_settings.starting_account_balance
        # Getting the main account balance
        main_account = MainAccount.objects.filter(profile=self.request.user.account)
        if main_account.aggregate(Sum('amount'))['amount__sum'] == None:
            account_balance = starting_balance
        else:
            account_balance = main_account.aggregate(Sum('amount'))['amount__sum']+starting_balance
        # Getting the profit account balance
        profit_account = ProfitAccount.objects.filter(profile=self.request.user.account)
        profit_balance = profit_account.aggregate(Sum('amount'))['amount__sum'] or 0
        # Getting the referral account balance
        referral_account = ReferralAccount.objects.filter(profile=self.request.user.account)
        referral_balance = referral_account.aggregate(Sum('amount'))['amount__sum'] or 0

        # Getting Total withdrawal
        withdrawals = Withdrawal.objects.filter(profile=self.request.user.account)
        total_withdrawal = withdrawals.count()
        # Getting Total Investment
        investments = Investment.objects.filter(profile=self.request.user.account)
        total_investment = investments.count()
        # Getting Pending Deposit
        pending_deposits = Deposit.objects.filter(profile=self.request.user.account, status='Pending')
        total_pending_deposits = pending_deposits.count()
        # Getting Pending Withdrawal
        pending_withdrawals= Withdrawal.objects.filter(profile=self.request.user.account, status='Pending')
        total_pending_withdrawals = pending_withdrawals.count()
        # Getting Completed Deposit
        completed_deposits = Deposit.objects.filter(profile=self.request.user.account, status='Completed')
        total_completed_deposits = completed_deposits.count()
        completed_deposit_balance = completed_deposits.aggregate(Sum('amount'))['amount__sum'] or 0
        # Getting Completed Investment
        completed_investments = Investment.objects.filter(profile=self.request.user.account, status='Completed')
        total_completed_investments = completed_investments.count()
        completed_investment_balance = completed_investments.aggregate(Sum('amount'))['amount__sum'] or 0
        # Getting Completed Withdrawal
        completed_withdrawals = Withdrawal.objects.filter(profile=self.request.user.account, status='Completed')
        total_completed_withdrawals = completed_withdrawals.count()
        # Getting Cancelled Investment
        cancelled_investments = Investment.objects.filter(profile=self.request.user.account, status='Cancelled')
        total_cancelled_investments = cancelled_investments.count()
        # Getting Ongoing Investment
        ongoing_investments = Investment.objects.filter(profile=self.request.user.account, status='Ongoing')
        total_ongoing_investments = ongoing_investments.count()

        # Getting the main account balance
        main_account = MainAccount.objects.filter(profile=self.request.user.account)
        main_account_balance = main_account.aggregate(Sum('amount'))['amount__sum'] or 0
        account_balance = main_account_balance+starting_balance+completed_deposit_balance-completed_investment_balance
        
        context['account_balance'] = account_balance
        context['profit_balance'] = profit_balance
        context['referral_balance'] = referral_balance
        context['total_withdrawal'] = total_withdrawal
        context['total_investment'] = total_investment
        context['total_pending_deposits'] = total_pending_deposits
        context['total_pending_withdrawals'] = total_pending_withdrawals
        context['total_completed_deposits'] = total_completed_deposits
        context['total_completed_investments'] = total_completed_investments
        context['total_cancelled_investments'] = total_cancelled_investments
        context['total_ongoing_investments'] = total_ongoing_investments
        context['total_completed_withdrawals'] = total_completed_withdrawals
        return context 

class DepositListView(LoginRequiredMixin,ListView):
    model = Deposit
    template_name = 'userdashboard/deposit_list.html'
    login_url = "auth_app:login"

class DepositCreateView(LoginRequiredMixin,CreateView):
    model = Deposit
    form_class = DepositForm
    template_name = 'userdashboard/new_deposit.html'
    success_url = reverse_lazy('crypto:deposit_list')
    redirect_field_name = "redirect_to"
    login_url = "auth_app:login"

    def form_valid(self, form):
        form.instance.profile = self.request.user.account
        return super().form_valid(form)
    
class DepositDetailView(LoginRequiredMixin, DetailView):
    model = Deposit
    template_name = 'userdashboard/deposit_detail.html'
    login_url = "auth_app:login"
    

class InvestmentListView(LoginRequiredMixin, ListView):
    model = Investment
    template_name = 'userdashboard/investment_list.html'
    login_url = "auth_app:login"

class InvestmentDetailView(LoginRequiredMixin, DetailView):
    model = Investment
    template_name = 'userdashboard/investment_detail.html'
    login_url = "auth_app:login"

class InvestmentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Investment
    form_class = InvestmentForm
    success_url = reverse_lazy('crypto:investment_list')
    template_name = 'userdashboard/new_investment.html'
    redirect_field_name = "redirect_to"
    success_message = "Investment was created successfully"
    login_url = "auth_app:login"

    def form_valid(self, form):
        form.instance.profile = self.request.user.account
        return super().form_valid(form)
    
    def form_invalid(self, form):
        amount_field = form.cleaned_data['amount']
        # user = self.instance.user
        transaction_settings = get_object_or_404(TransactionSettings, pk=1)
        starting_balance = transaction_settings.starting_account_balance
        # Getting Completed Deposit
        completed_deposits = Deposit.objects.filter(profile=self.request.user.account, status='Completed')
        total_completed_deposits = completed_deposits.count()
        completed_deposit_balance = completed_deposits.aggregate(Sum('amount'))['amount__sum'] or 0
        # Getting Completed Investment
        completed_investments = Investment.objects.filter(profile=self.request.user.account, status='Completed')
        total_completed_investments = completed_investments.count()
        completed_investment_balance = completed_investments.aggregate(Sum('amount'))['amount__sum'] or 0
        # Getting the main account balance
        main_account = MainAccount.objects.filter(profile=self.request.user.account)
        main_account_balance = main_account.aggregate(Sum('amount'))['amount__sum'] or 0
        account_balance = main_account_balance+starting_balance+completed_deposit_balance-completed_investment_balance
        # amount_field.validators.append(MinValueValidator(account_balance))

        if amount_field > account_balance:
            form.add_error('amount', 'Your account is low. Kindly fund your account')
            return self.form_invalid(form)

        return super().form_valid(form)

class WithdrawalListView(LoginRequiredMixin, ListView):
    model = Withdrawal
    template_name = 'userdashboard/withdrawal_list.html'
    login_url = "auth_app:login"

class WithdrawalDetailView(LoginRequiredMixin, DetailView):
    model = Withdrawal
    template_name = 'userdashboard/withdrawal_detail.html'
    login_url = "auth_app:login"

class WithdrawalCreateView(LoginRequiredMixin, CreateView):
    model = Withdrawal
    form_class = WithdrawalForm
    success_url = reverse_lazy('crypto:withdrawal_list')
    template_name = 'userdashboard/new_withdrawal.html'
    redirect_field_name = "redirect_to"
    login_url = "auth_app:login"

    def form_valid(self, form):
        form.instance.profile = self.request.user.account
        return super().form_valid(form)

crypto/templates/userdashboard/deposit_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'userdashboard/base.html' %} {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% block title %}
    <title>Deposit List</title>
    {% endblock title %}
    <link rel="stylesheet" href="/static/css/dashboard.css">
</head>

<body>
    {% block content %}
    <div class="dashboard-content">
        <div class="content-title">
            <h1>Deposit List</h1>
        </div>
        <div class="content table-list-card">
            <div class="table-list-heading">
                <div class="table-title">List</div>
                <div class="show-entries input-entry">
                    <form action="" method="get">
                        <label for="entries">Show</label> <input type="number" name="entries" id="entries">
                        <span>entries</span>
                    </form>
                </div>
                <div class="search-table input-entry">
                    <form action="" method="post">
                        <label for=" search ">Search: </label> <input type="search" name="search" id="search" placeholder="Search">
                    </form>

                </div>
            </div>
            <div class="table-content">
                <table>
                    <thead>
                        <tr>
                            <th>Reference</th>
                            <th>Amount</th>
                            <th>Asset</th>
                            <th>Deposit Ref</th>
                            <th> Date Initiated</th>
                            <th>Status</th>
                            <th>View</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                        <tr>
                            <td>{{item.reference}}</td>
                            <td>{{item.amount|floatformat:"2g"}}</td>
                            <td>
                                <div class="asset-type">
                                    <div class="asset-image"><img src="{{item.asset.asset_icon.url}}" alt="{{item.asset.asset_abbr}}"></div>

                                    <div>
                                        <p class="asset-fullname">{{item.asset.asset_name}}</p>
                                        <p class="asset-shortname">{{item.asset.asset_abbr}}</p>
                                    </div>
                                </div>

                            </td>
                            <td>{{item.reference}}</td>
                            <td>{{item.date_initiated}}</td>
                            <td class="trans-{{item.status}}">
                                <p>{{item.status}}</p>
                            </td>
                            <td>
                                <a href="{% url 'crypto:deposit_detail' item.slug %}" class="view-detail">View detail</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% endblock content %}
</body>

</html>

crypto/templates/userdashboard/investment_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'userdashboard/base.html'%} {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% block title %}
    <title>Investment List</title>
    {% endblock %}
    <link rel="stylesheet" href="/static/css/dashboard.css">
</head>

<body>
    {% block content %}
    <div class="dashboard-content">
        <div class="content-title">
            <h1>Investment List</h1>
        </div>
        <div class="content table-list-card">
            <div class="table-list-heading">
                <div class="table-title">List</div>
                <div class="show-entries input-entry">
                    <form action="" method="get">
                        <label for="entries">Show</label> <input type="number" name="entries" id="entries">
                        <span>entries</span>
                    </form>
                </div>
                <div class="search-table input-entry">
                    <form action="" method="post">
                        <label for=" search ">Search: </label> <input type="search" name="search" id="search" placeholder="Search">
                    </form>

                </div>
            </div>
            <div class="table-content">
                <table>
                    <thead>
                        <tr>
                            <th>Reference</th>
                            <th>Amount</th>
                            <th>ROI</th>
                            <th>Current profit</th>
                            <th>Date Initiated</th>
                            <th>Status</th>
                            <th>View</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %} {% if item %}
                        <tr>
                            <td>{{item.reference}}</td>
                            <td>{{item.amount|floatformat:"2g"}}</td>
                            <td>{{item.package.roi}}%</td>
                            <td>{{item.current_profit|floatformat:"2g"}}</td>
                            <td>{{item.date_initiated}}</td>
                            <td class="trans-{{item.status}}">
                                <p>{{item.status}}</p>
                            </td>
                            <td>
                                <a href="{% url 'crypto:investment_detail' item.slug %}" class="view-detail">View detail</a>
                            </td>
                        </tr>
                        {% endif %} {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% endblock content %}
</body>

</html>

crypto/templates/userdashboard/new_deposit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'userdashboard/base.html' %} {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% block title %}
    <title>Document</title>
    {% endblock title %}
    <link rel="stylesheet" href="/static/css/dashboard.css">
</head>

<body>
    {% block content %}
    <div class="dashboard-content">
        <div class="content-title">
            <h1>New Deposit</h1>
        </div>
        <div class="content table-list-card">
            <div class="table-list-heading">
                <div class="table-title">New Deposit</div>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-card">
                        <label for="name">Name</label><br> <input type="text" name="name" id="name" value="{{request.user.first_name}}" disabled>
                    </div>
                    <div class="input-card">
                        <label for="email">Email</label> <br>
                        <input type="email" name="email" id="email" value="{{request.user.email}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-card">
                        <label for="minimum_deposit">Minimum Deposit ($)</label><br>
                        <input type="number" name="minimum_deposit" id="minimum_deposit" value="{{transaction_settings.minimum_deposit}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-card">
                        <label for="{{form.amount.id_for_label}}">Amount ($)</label><br>{{form.amount.errors}}{{form.amount}}
                    </div>
                    <div class="input-card">
                        <label for="{{ form.asset.id_for_label }}">Asset</label> <br> {{ form.asset.errors }} {{form.asset}}
                    </div>
                </div>
                <div class="deposit-button">
                    <input class="copy-btn" type="submit" value="Deposit">
                </div>
            </form>
        </div>
    </div>
    {% endblock content %}
</body>

</html>

crypto/templates/userdashboard/new_investment.html
<!DOCTYPE html>
<html lang="en">
{% extends 'userdashboard/base.html' %} {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% block title %}
    <title>New Investment</title>
    {% endblock title %}
    <link rel="stylesheet" href="/static/css/dashboard.css">
</head>

<body>
    {% block content %}
    <div class="dashboard-content">
        <div class="content-title">
            <h1>New Investment</h1>
        </div>
        <div class="content table-list-card">
            <div class="table-list-heading">
                <div class="table-title">New Investment</div>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-card">
                        <label for="name">Name</label><br> <input type="text" name="name" id="name" value="{{request.user.first_name}}" disabled>
                    </div>
                    <div class="input-card">
                        <label for="email">Email</label> <br>
                        <input type="email" name="email" id="email" value="{{request.user.email}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-card">
                        <label for="amount">Amount ($)</label><br>{{form.amount.errors}} {{form.amount}}
                    </div>
                    <div class="input-card">
                        <label for="{{form.package.id_for_label}}">Package</label> <br>{{form.package.errors}} {{form.package}}
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-card">
                        <label for="{{ form.account.id_for_label }}">Account</label> <br> {{ form.account.errors }} {{form.account}}
                    </div>
                </div>
                <div class="deposit-button">
                    <input class="copy-btn" type="submit" value="Invest">
                </div>
            </form>
        </div>
    </div>
    {% endblock content %}
</body>

</html>

crypto/templates/userdashboard/withdrawal_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'userdashboard/base.html' %} {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">{% block title %}
    <title>Withdrawal List</title>
    {% endblock title %}
    <link rel="stylesheet" href="/static/css/dashboard.css">
</head>

<body>
    {% block content %}
    <div class="dashboard-content">
        <div class="content-title">
            <h1>Withdrawal List</h1>
        </div>
        <div class="content table-list-card">
            <div class="table-list-heading">
                <div class="table-title">List</div>
                <div class="show-entries input-entry">
                    <form action="" method="get">
                        <label for="entries">Show</label> <input type="number" name="entries" id="entries">
                        <span>entries</span>
                    </form>
                </div>
                <div class="search-table input-entry">
                    <form action="" method="post">
                        <label for=" search ">Search: </label> <input type="search" name="search" id="search" placeholder="Search">
                    </form>

                </div>
            </div>
            <div class="table-content">
                <table>
                    <thead>
                        <tr>
                            <th>Reference</th>
                            <th>Amount</th>
                            <th>Wallet address</th>
                            <th>Asset</th>
                            <th> Date Requested</th>
                            <th>Status</th>
                            <th>View</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                        <tr>
                            <td>{{item.reference}}</td>
                            <td>{{item.amount|floatformat:"2g"}}</td>
                            <td>{{item.wallet_address}}</td>
                            <td>
                                <div class="asset-type">
                                    <div class="asset-image"><img src="{{item.asset.asset_icon.url}}" alt="{{item.asset.asset_abbr}}"></div>

                                    <div>
                                        <p class="asset-fullname">{{item.asset.asset_name}}</p>
                                        <p class="asset-shortname">{{item.asset.asset_abbr}}</p>
                                    </div>
                                </div>
                            </td>
                            <td>{{item.date_requested}}</td>
                            <td class="trans-{{item.status}}">
                                <p>{{item.status}}</p>
                            </td>
                            <td>
                                <a href="{% url 'crypto:withdrawal_detail' item.slug %}" class="view-detail">View detail</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% endblock content %}
</body>

</html>