auth_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import authentication
app_name = 'auth_app'

urlpatterns = [

    # Signup and SignIn URL
    path(
        route='signup',
        view=authentication.UserRegisterView.as_view(),
        name='signup'
    ),
    path(
        route='email-verification-confirm',
        view=authentication.EmailVerificationConfirm.as_view(),
        name='email_verification_confirm'
    ),
    path(
        route='email-verification/invalid-link',
        view=authentication.EmailVerificationInvalid.as_view(),
        name='email_verification_invalid'
    ),
    path(
        route='login',
        view=authentication.UserLoginView.as_view(),
        name='login'
    ),
    path('logout', authentication.LogoutView.as_view(), name='logout'),

    # Reset Password URLS

    path(
        route='reset-password',
        view=authentication.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path('password-reset/done/', authentication.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         authentication.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset_complete/done/', authentication.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-change', authentication.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', authentication.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('activate/<uidb64>/<token>/',
         authentication.activate, name='activate'),
]

crypto_inv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('crypto.urls')),
    path('auth/', include('auth_app.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'main'

urlpatterns = [
    path(route='', view=views.Home.as_view(), name='home'),
]

auth_app/models.py
from django.db import models

# Create your models here.

auth_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    """
        Creates User registration form for signing up.
    """

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.pop("autofocus", None)

    email = forms.EmailField(max_length=254, required=True, widget=forms.EmailInput(attrs={
        "name": "email", "class": "input100",
        "placeholder": "Email"
    }
    ),
        help_text='Required. Input a valid email address.'
    )
    password1 = forms.CharField(label="Password",
    widget=forms.PasswordInput(attrs={
        "name": "password", "class": "input100",
        "placeholder": "Password"
    }
    ),
    )

    password2 = forms.CharField(label="Confirm Password",
                                help_text=_(
                                    "Enter the same password as before, for verification."),
    widget=forms.PasswordInput(attrs={
        "name": "Confirm Password", "class": "input100",
        "placeholder": "Confirm Password"
    }

    ),
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {

            "username": forms.TextInput(attrs={
                "name": "username", "class": "input100",
                "placeholder": "Username"
            }),
        }

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

auth_app/views/authentication.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib import messages
from .tokens import account_activation_token
from django.http.response import HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView
from django.contrib.auth.views import (PasswordResetDoneView, PasswordResetConfirmView,
                                        PasswordResetCompleteView, PasswordChangeView,
                                       PasswordChangeDoneView, PasswordResetView, LogoutView)
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic import View
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import (
    AuthenticationForm,
)
from django.urls import reverse_lazy
from auth_app.forms import UserRegisterForm

from crypto.models import SiteSettings
from django.shortcuts import get_object_or_404
site_setting = get_object_or_404(SiteSettings, pk=1)
company_email = site_setting.company_email
# company_email = 'jetticons@gmail.com'

class UserLoginView(View):
    """
     Logs user into dashboard.
    """
    template_name = 'authentication/login.html'
    context_object = {"login_form": AuthenticationForm}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context_object)

    def post(self, request, *args, **kwargs):

        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            
            login(request, user)
            messages.success(request, f"Login Successful ! "
                                f"Welcome {user.username}.")
            return redirect('crypto:dashboard')

        else:
            messages.error(request,
                           f"Please enter a correct username and password. Note that both fields may be case-sensitive."
                           )
            return render(request, self.template_name, self.context_object)
        


class LogoutView(LogoutView):
    template_name = 'authentication/logged_out.html'
    
class PasswordResetView(PasswordResetView):
    template_name = 'authentication/pwd_reset_form.html'
    email_template_name = "authentication/email_text/password_reset_email.html"
    from_email = company_email
    subject_template_name = "authentication/email_text/password_reset_subject.txt"
    success_url = reverse_lazy("auth_app:password_reset_done")

class PasswordResetDoneView(PasswordResetDoneView):
    template_name = 'authentication/password_reset_done.html' 

class PasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'authentication/password_reset_confirm.html'
    success_url = reverse_lazy("auth_app:password_reset_complete")

class PasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'authentication/password_reset_complete.html'

class PasswordChangeView(PasswordChangeView):
    template_name = 'authentication/password_change_form.html'
    success_url = reverse_lazy("auth_app:password_change_done")

class PasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'authentication/password_change_done.html'




UserModel = get_user_model()


class UserRegisterView(View):
    """
      View to let users register
    """
    template_name = 'authentication/register.html'
    context = {
        "register_form": UserRegisterForm()
    }

    def get(self, request):
        success_message = "Successful"
        self.context['success_message'] = success_message
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):

        register_form = UserRegisterForm(request.POST)

        if register_form.is_valid():
            user = register_form.save(commit=False)
            user.is_active = True
            user.is_staff = True
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('authentication/activate_email.html'
                                       , {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
                'protocol': 'http',
            }
            )
            from_email = company_email
            to_email = register_form.cleaned_data.get('email')
            print(to_email)
            print(message)
            email = EmailMessage(
                mail_subject, message, from_email, to=[to_email]
            )
            email.send()

            return HttpResponseRedirect(reverse_lazy('auth_app:email_verification_confirm'))

        else:
            messages.error(request, "Please provide valid information.")
            # Redirect user to register page
            return render(request, self.template_name, self.context)

    def get_success_url(self):
        return reverse('main:home')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(
            request, f'Hi {user.username}, your registration was successful!! .')
        return reverse('main:home')
    else:
        return reverse_lazy('auth_app:email_verification_invalid')


class EmailVerificationConfirm(TemplateView):
    template_name = 'authentication/email_verification_confirm.html'


class EmailVerificationInvalid(TemplateView):
    template_name = 'authentication/email_verification_invalid.html'

auth_app/views/tokens.py
from django.contrib.auth.tokens import PasswordResetTokenGenerator
import six


class AccountActivationTokenGenerator(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (
            six.text_type(user.pk) + six.text_type(timestamp) +
            six.text_type(user.is_active)
        )


account_activation_token = AccountActivationTokenGenerator()

crypto/views/authentication.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib import messages
from .tokens import account_activation_token
from django.http.response import HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView
from django.contrib.auth.views import (PasswordResetDoneView, PasswordResetConfirmView,
                                        PasswordResetCompleteView, PasswordChangeView,
                                       PasswordChangeDoneView, PasswordResetView)
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic import View
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import (
    AuthenticationForm,
)
from django.urls import reverse_lazy
from crypto.forms import UserRegisterForm

class UserLoginView(View):
    """
     Logs user into dashboard.
    """
    template_name = 'registration/login.html'
    context_object = {"login_form": AuthenticationForm}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context_object)

    def post(self, request, *args, **kwargs):

        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            
            login(request, user)
            messages.success(request, f"Login Successful ! "
                                f"Welcome {user.username}. Update your User profile if you have not done so. Ignore this message if your User profile is upto date.")
            return redirect('ue_app:home')

        else:
            messages.error(request,
                           f"Please enter a correct username and password. Note that both fields may be case-sensitive."
                           )
            return render(request, self.template_name, self.context_object)
        



class PasswordResetView(PasswordResetView):
    template_name = 'registration/pwd_reset_form.html'
    email_template_name = "registration/email_text/password_reset_email.html"
    from_email = 'lekiaprosper@gmail.com'
    subject_template_name = "registration/email_text/password_reset_subject.txt"
    success_url = reverse_lazy("ue_app:password_reset_done")

class PasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/email_text/password_reset_done.html' 

class PasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/email_text/password_reset_confirm.html'
    success_url = reverse_lazy("ue_app:password_reset_complete")

class PasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/email_text/password_reset_complete.html'

class PasswordChangeView(PasswordChangeView):
    template_name = 'registration/email_text/password_change_form.html'
    success_url = reverse_lazy("ue_app:password_change_done")

class PasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'registration/email_text/password_change_done.html'




UserModel = get_user_model()


class UserRegisterView(View):
    """
      View to let users register
    """
    template_name = 'registration/register.html'
    context = {
        "register_form": UserRegisterForm()
    }

    def get(self, request):
        success_message = "Successful"
        self.context['success_message'] = success_message
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):

        register_form = UserRegisterForm(request.POST)

        if register_form.is_valid():
            user = register_form.save(commit=False)
            user.is_active = True
            user.is_staff = True
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('registration/activate_email.html'
                                       , {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
                'protocol': 'http',
            }
            )
            from_email = 'prosperlekia@gmail.com'
            to_email = register_form.cleaned_data.get('email')
            print(to_email)
            print(message)
            email = EmailMessage(
                mail_subject, message, from_email, to=[to_email]
            )
            email.send()

            return HttpResponseRedirect(reverse_lazy('ue_app:email_verification_confirm'))

        else:
            messages.error(request, "Please provide valid information.")
            # Redirect user to register page
            return render(request, self.template_name, self.context)

    def get_success_url(self):
        return reverse('ue_app:home')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(
            request, f'Hi {user.username}, your registration was successful!! .')
        return reverse('ue_app:home')
    else:
        return reverse_lazy('ue_app:email_verification_invalid')


class EmailVerificationConfirm(TemplateView):
    template_name = 'registration/email_verification_confirm.html'


class EmailVerificationInvalid(TemplateView):
    template_name = 'registration/email_verification_invalid.html'

auth_app/templates/authentication/activate_email.html
{% autoescape off %} Hi {{ user.username }}, Please click on the link to confirm your registration, http://{{ domain }}{% url 'auth_app:activate' uidb64=uid token=token %} If you think, it's not you, then just ignore this email. {% endautoescape %}

auth_app/templates/authentication/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% block title %} {% endblock title %} {% block styles %}
    <link rel="stylesheet" href="/static/css/style.css"> {% endblock styles %}
</head>

<body>
    <main>
        <div class="main-container">
            {% block messages %} {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
                {% endfor %}
            </div>
            {% endif %} {% endblock messages %} {% block content %} {% endblock content %}
        </div>
    </main>
    {% block scripts %} {% endblock scripts %}
</body>

</html>

auth_app/templates/authentication/email_verification_confirm.html
{% extends 'authentication/base.html' %} {% load i18n %} {% block content %}
<div class="display-sign-container" style="z-index: 1000;">
    <div class="sign-up-container">

        <div class="sign-up-card">
            <h5>Please confirm your email address to complete the registration.</h5>
        </div>
        <a class="create-profile-link" href="{% url 'main:home' %}">Return home</a>
    </div>
</div>

{% endblock content %}

auth_app/templates/authentication/email_verification_invalid.html
{% extends 'authentication/base.html' %} {% load i18n %} {% block content %}
<div class="display-sign-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            <h5>Activation link is invalid!.</h5>
        </div>
    </div>
    <a class="create-profile-link" href="{% url 'main:home' %}">Return home</a>
</div>

{% endblock content %}

auth_app/templates/authentication/logged_out.html
{% extends "authentication/base.html" %} {% load i18n %} {% block content %}
<div class="display-sign-container">
    <div class=" sign-up-card ">
        <h1>Logged out!</h1> <br>
        <a href="{% url 'auth_app:login'%} ">Click here to login again.</a> <br> <br>
        <p>OR</p><br>
        <a class="create-profile-link " href="{% url 'main:home' %} ">Return home</a>{% endblock %}
    </div>

</div>

auth_app/templates/authentication/login.html
{% extends 'authentication/base.html' %} {% block content %}

<div class="display-sign-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            <h1>Login</h1>{% if login_form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
            {% endif %} {% if next %} {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
            {% else %}
            <p>Please login to see this page.</p>
            {% endif %} {% endif %}
            <form method="post" action="{% url 'auth_app:login' %}">
                {% csrf_token %}
                <div class="form-container">
                    {{ login_form }}
                </div>
                <input class="sign-up-button" type="submit" value="Login" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
            <!-- <div class="showpassword-container">
                <input type="checkbox" onclick="showPassword(this)">
                <p class="showpassword-text">Show Password</p>
            </div> -->
            {# Assumes you setup the password_reset view in your URLconf #}
            <p><a href="{% url 'auth_app:password_reset' %}" class="text-info">Lost password?</a>
            </p>
            <a class="create-profile-link" href="{% url 'main:home' %}">Return home</a>
        </div>
    </div>
</div>
{% endblock content %}

auth_app/templates/authentication/password_change_done.html
 {% extends 'authentication/base.html' %}


<div class="display-sign-container">
    <div class=" sign-up-card ">
        <p>You have successfully changed your password</p>

        <a href="{% url 'auth_app:login' %}"></a><a class="create-profile-link" href="{% url 'main:home' %}">Return home</a>
    </div>
</div>

auth_app/templates/authentication/password_change_form.html
{% extends 'authentication/base.html' %} {% load i18n %} {% block content %}

<div class="display-sign-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            <h2 class="font-weight-bold">Enter New Password</h2>
            <p>Kindly enter a new password.</p>
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-container">
                    {{ form }}
                </div>
                <input type="submit" class="sign-up-button" value="Submit">
            </form>
            <a class="create-profile-link" href="{% url 'main:home' %}">Return home</a>
        </div>
    </div>
</div>
{% endblock %}

auth_app/templates/authentication/password_reset_complete.html
{% extends 'authentication/base.html' %} {% block content %}
<div class="display-sign-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            <h1>The password has been changed!</h1>
            <p><a class="text-info" href="{% url 'auth_app:login' %}">log in again?</a></p>
            <a class="create-profile-link" href="{% url 'main:home' %}">Return home</a>
        </div>
    </div>
</div>
{% endblock content %}

auth_app/templates/authentication/password_reset_confirm.html
{% extends 'authentication/base.html' %} {% block content %}
<div class="display-sign-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            {% if validlink %}
            <p>Please enter (and confirm) your new password.</p>
            <form action="" method="post">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>{{ form.new_password1.errors }}
                            <label for="id_new_password1">New password:</label>
                        </td>
                        <td>{{ form.new_password1 }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.new_password2.errors }}
                            <label for="id_new_password2">Confirm password:</label>
                        </td>
                        <td>{{ form.new_password2 }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Change my password" /></td>
                    </tr>
                </table>
            </form>
            {% else %}
            <h2>Password reset failed</h2>
            <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.
            </p>
            {% endif %}
            <a class="create-profile-link" href="{% url 'main:home' %}">Return home</a>
        </div>
    </div>
</div>
{% endblock content %}

auth_app/templates/authentication/password_reset_done.html
{% extends 'authentication/base.html' %} {% load i18n %} {% block content %}
<div class="display-sign-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            <h5>We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check your spam folder.
            </h5>
            <a class="create-profile-link" href="{% url 'main:home' %}">Return home</a>
        </div>
    </div>
</div>

{% endblock content %}

auth_app/templates/authentication/pwd_reset_form.html
 {% extends 'authentication/base.html' %} {% block content %}
<div class="display-sign-container">
    <div class=" sign-up-container">
        <div class="sign-up-card">
            <div>
                <h2 class="font-weight-bold ">Reset Password</h2>
                <p class="forget-password-text ">Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
            </div>
            <form method="post " action="{% url 'auth_app:password_reset' %} ">
                {% csrf_token %}
                <div class="form-container ">
                    {{ form }}
                </div>
                <input class="sign-up-button " type="submit " value="Reset password " />
            </form>
            <a class="create-profile-link " href="{% url 'main:home' %} ">Return home</a>
        </div>
    </div>
</div>
{% endblock content %}

auth_app/templates/authentication/register.html
{% extends 'authentication/base.html' %} {% block content %}

<div class="display-sign-container">
    <div class=" sign-up-container">
        <div class="sign-up-card">
            <h1 class="center ">Sign Up</h1>
            {{register_form.errors}}
            <form action="{% url 'auth_app:signup' %} " method="post" novalidate>
                {% csrf_token %}
                <div class="form-container">
                    {% for field in register_form %}
                    <div class="fieldWrapper ">
                        {% if field.errors %}
                        <ul>
                            {% for error in field.errors %}
                            <li class="error"><strong>{{error|escape}}</strong></li>
                            {% endfor %}
                        </ul>
                        {% endif %} {{field.label_tag}}
                        <br> {{field}} {% if field.help_text %}
                        <p class="help"></p>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                <input class="sign-up-button" type="submit" value="Submit">
            </form>
            <!-- <div class="showpassword-container ">
                <input type="checkbox " onclick="showPassword(this) ">
                <p class="showpassword-text ">Show Password</p>
            </div> -->
            <!-- <hr /> -->
            <div class="text-center ">
                <a class="small text-info " href="{% url 'auth_app:login' %} ">Already Have an Account!</a>
            </div>
            <div class="text-center ">
                <a class="small text-info " href="{% url 'main:home' %} ">
                    Home
                </a>
            </div>
        </div>
    </div>
</div>

<script>
    let password1Input = document.querySelector("input[name='password1' ] ");
    let password2Input = document.querySelector("input[name='password2' ] ");

    setInterval(() => {
        if (password2Input.value == password1Input.value) {
            password2Input.style.color = 'green';
        } else {
            password2Input.style.color = 'red';
        }
    }, 500);
</script>

{% endblock content %}